version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Lisbon"
    target-branch: "main"
    labels: ["dependencies","automated pr"]
    reviewers: ["jtlivio"]
    assignees: ["jtlivio"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Lisbon"
    target-branch: "main"
    labels: ["ci","dependencies","automated pr"]
