# .github/FUNDING.yml
# Configure the "Sponsor" button on GitHub.

# When GitHub Sponsors is active for your user/org,
# uncomment the lines below and keep only valid accounts.
# github:
#   - jtlivio

# Other platforms (do not require GitHub validation)
# patreon: ph7xsystems
open_collective: p7co
# ko_fi: ph7xsystems

# Custom links
custom:
#  - https://p7co.org
