# Configure the "Sponsor" button on GitHub.

# When GitHub Sponsors is active for your user/org,
# uncomment the lines below and keep only valid accounts.
# github:
#   - jtlivio

# Other platforms (do not require GitHub validation)
patreon: p7co
open_collective: p7co
# ko_fi: p7co

# Custom links
custom:
#  - https://p7co.org
