# FUNDING.yml

# GitHub Sponsors (requer ativação na conta GitHub)
#github: [jtlivio]

patreon: p7co
# open_collective: p7co
# ko_fi: p7co

# Links personalizados (opcional)
custom: ['https://p7co.org']