base_path: .
preserve_hierarchy: true

files:
  - source: /ui/en/**/*.json
    translation: /ui/%two_letters_code%/**/%original_file_name%

  - source: /content/blog/en/**/*.md
    translation: /content/blog/%two_letters_code%/**/%original_file_name%
