# crowdin.yml (fixed)
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_url: "https://api.crowdin.com"
base_path: .
preserve_hierarchy: true
# English is the source language
source_language: "en"

files:
  # UI JSON (EN -> others)
  - source: "/ui/en/**/*.json"
    translation: "/ui/%two_letters_code%/%original_path%/%original_file_name%"

  # Blog posts (EN -> others)
  - source: "/content/blog/en/**/*.md"
    translation: "/content/blog/%two_letters_code%/%original_path%/%original_file_name%"
