project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
preserve_hierarchy: true

files:
  # UI strings (English is source)
  - source: /ui/en/**/*.json
    translation: /ui/%two_letters_code%/**/%original_file_name%

  # Blog posts (English is source)
  - source: /content/blog/en/**/*.md
    translation: /content/blog/%two_letters_code%/**/%original_file_name%
