# Língua-fonte: en (definida no projeto Crowdin)
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  # UI JSON (ex.: static/ui/en/components/navbar.json)
  - source: /static/ui/en/**/*.json
    translation: /static/ui/%two_letters_code%/**/%original_file_name%

  # Conteúdo do blog em Markdown
  - source: /static/content/blog/en/**/*.md
    translation: /static/content/blog/%two_letters_code%/**/%original_file_name%
