# Língua-fonte: en (definida no projeto)
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  # UI (LEGADO – se ainda existir)
  - source: /ui/en/**/*.json
    translation: /ui/%two_letters_code%/**/%original_file_name%

  # UI (NOVA árvore em static/)
  - source: /static/ui/en/**/*.json
    translation: /static/ui/%two_letters_code%/**/%original_file_name%

  # Blog (LEGADO – se ainda existir)
  - source: /content/blog/en/**/*.md
    translation: /content/blog/%two_letters_code%/**/%original_file_name%

  # Blog (NOVA árvore em static/)
  - source: /static/content/blog/en/**/*.md
    translation: /static/content/blog/%two_letters_code%/**/%original_file_name%
