name: "📑 Article Proposal (Form)"
description: "Propose a new in-depth article, whitepaper, or technical guide for the P7CO® EcoResupply blog."
title: "feat(content): article proposal — <short title>"
labels: ["article", "content/article"]
assignees: []
body:
  - type: input
    id: title
    attributes:
      label: Proposed Title
      placeholder: "Example: GDPR Compliance in Circular Economy Platforms"
    validations:
      required: true

  - type: textarea
    id: abstract
    attributes:
      label: Abstract / Main Idea
      description: "Summarize the core message and scope of the article"
      placeholder: "This article will analyze..."
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: Initial Language
      options:
        - English (en)
        - Portuguese (pt)
        - Spanish (es)
        - French (fr)
        - German (de)
    validations:
      required: true

  - type: dropdown
    id: kind
    attributes:
      label: Type
      options:
        - Whitepaper
        - Technical Guide
        - Case Study
        - Report
        - News / Update
        - Opinion / Editorial
    validations:
      required: true

  - type: checkboxes
    id: category
    attributes:
      label: Category (choose one or more)
      options:
        - label: guides
        - label: news
        - label: case-studies
        - label: esg
        - label: tech
        - label: p7co
        - label: policy
        - label: community
        - label: innovation
        - label: circularity
        - label: events
        - label: opinion
        - label: analysis
        - label: whitepaper
        - label: report
        - label: insight
        - label: legal
        - label: environment
        - label: market
        - label: services
        - label: about
        - label: faq

  - type: textarea
    id: target_audience
    attributes:
      label: Target Audience & Use-Cases
      placeholder: "SMEs, municipalities, recyclers, logistics, NGOs, academia..."
    validations:
      required: true

  - type: textarea
    id: outline
    attributes:
      label: Outline / Sections
      placeholder: |
        1. Context
        2. Problem / Opportunity
        3. Method / Approach
        4. Examples
        5. Takeaways
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References / Sources (if any)
      placeholder: "Links to regulations, standards, datasets, or prior posts"

  - type: input
    id: hero_image
    attributes:
      label: Hero Image (path)
      description: "Relative path under images/ or proxy URL: /proxy/image?path=images/..."
      placeholder: "/proxy/image?path=images/article-template.jpg"

  - type: checkboxes
    id: extras
    attributes:
      label: Extras
      options:
        - label: Needs translation
        - label: Requires SME review
        - label: Include code samples
