name: "🐞 Bug Report"
description: "Report an error, unexpected behavior, or broken functionality"
title: "[BUG] Short description"
labels: ["bug"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Explain the issue you encountered and what you expected to happen"
      placeholder: "The system does X, but I expected Y..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Provide the steps to reproduce the issue"
      placeholder: |
        1. Go to...
        2. Click on...
        3. See the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What should have happened instead?"
      placeholder: "The feature should..."

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots / Logs"
      description: "Attach screenshots or relevant logs if applicable"
      placeholder: "Drag & drop screenshots or paste logs here"

  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: "System, browser, version, or other environment details"
      placeholder: "Example: macOS 14.5, Chrome 117, Node.js 20.0"

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here"
      placeholder: "Links to related issues, dependencies, etc."

  - type: checkboxes
    id: privacy
    attributes:
      label: "GDPR & Privacy Check"
      description: "Confirm you have not included any personal data (emails, phone numbers, IDs) in this report"
      options:
        - label: "I confirm this report contains no personal data"
          required: true
