name: "🌍 Translation Request"
description: "Request or propose a translation of an existing content file (Blog, Page, or Article)"
labels: ["translation", "content"]
body:
  - type: input
    id: original
    attributes:
      label: Original File URL or Path
      description: "Provide the link or repository path to the original Markdown file"
      placeholder: "https://github.com/jtlivio/P7CO/content/blog/en/example.md"
    validations:
      required: true

  - type: dropdown
    id: target_language
    attributes:
      label: Target Language
      options:
        - English (en)
        - Portuguese (pt)
        - Spanish (es)
        - French (fr)
        - German (de)
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes / Terminology
      description: "Add specific terminology, tone, or cultural notes for translators"
      placeholder: "Use 'circular economy' instead of 'green economy'..."
