name: Content Lint

on:
  pull_request:
    branches: [ main ]
    paths:
      - "content/**"
      - "images/**"
      - "ui/**"
      - "tools/**"
      - "package.json"
      - "package-lock.json"
  push:
    branches: [ main ]
    paths:
      - "content/**"
      - "images/**"
      - "ui/**"
      - "tools/**"
      - "package.json"
      - "package-lock.json"

permissions:
  contents: read

concurrency:
  group: content-lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint content & assets
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: "npm"

      - name: Show tool versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run content linter
        run: npm run lint:content
