name: Crowdin Sync

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "content/**"
      - "ui/**"
      - "crowdin.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "content/**"
      - "ui/**"
      - "crowdin.yml"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Crowdin Action
        uses: crowdin/github-action@v2
        with:
          upload_translations: true
          download_translations: true
          config: crowdin.yml
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
