name: Crowdin Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches-ignore: [ l10n_main ]
    paths:
      - "crowdin.yml"
      - "static/ui/**"
      - "static/content/**"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: crowdin-sync
  cancel-in-progress: true

jobs:
  sync:
    if: ${{ github.ref_name != 'l10n_main' && github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Crowdin Sync
        uses: crowdin/github-action@v2
        with:
          upload_translations: true
          download_translations: true
          crowdin_branch_name: l10n_main
          config: crowdin.yml