name: Crowdin Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches: [ main ]
    paths:
      - "crowdin.yml"
      - "static/ui/**"
      - "static/content/**"
      - "ui/**"
      - "content/blog/**"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: crowdin-sync
  cancel-in-progress: true

jobs:
  sync:
    if: ${{ github.ref_name != 'l10n_main' && github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Crowdin Sync
        uses: crowdin/github-action@v2
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        with:
          config: crowdin.yml
          upload_sources: true
          upload_sources_args: "--delete-obsolete"   # <-- apaga no Crowdin o que saiu do config/repos
          upload_translations: false
          download_translations: false
          localization_branch_name: l10n_main
          commit_message: "chore(l10n): batch Crowdin sync"
          create_pull_request: true
          pull_request_title: "chore(l10n): Crowdin batch sync"
          pull_request_body: |
            🤖 Automated Crowdin sync.
            Please verify lint/content rules and image constraints.
          pull_request_labels: l10n, crowdin
          pull_request_assignees: jtlivio
