name: Crowdin Sync

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "crowdin.yml"
      - "ui/**"
      - "content/**"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin Sync
        uses: crowdin/github-action@v2
        with:
          config: crowdin.yml
          upload_sources: true
          upload_translations: false
          download_translations: false
          localization_branch_name: l10n_main
          commit_message: "chore(l10n): sync from Crowdin"
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
