name: Deploy Static to Azure Storage (smart SHA)

on:
  push:
    branches: [ main ]
    paths: [ "static/**" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-static-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload only changed files by SHA (AAD)
        uses: azure/cli@v2
        with:
          inlineScript: |
            set -euo pipefail
            ACCOUNT="p7costatic"

            # precisamos de git no container do azure/cli para calcular o diff
            apt-get update -y >/dev/null 2>&1 || true
            apt-get install -y git >/dev/null 2>&1 || true

            # sanity: acesso AAD ao $web (propagação de RBAC)
            for n in 1 2 3 4 5 6; do
              if az storage blob list --account-name "$ACCOUNT" -c '$web' --auth-mode login --num-results 1 >/dev/null 2>&1; then
                echo "AAD access to ${ACCOUNT}/\$web OK"
                break
              fi
              echo "A aguardar propagação de RBAC… tentativa $n/6"
              sleep 10
            done

            # gama de comparação (último commit vs anterior)
            BASE="$(git rev-parse HEAD^ || echo '')"
            HEAD="$(git rev-parse HEAD)"
            if [ -z "$BASE" ]; then
              # primeiro commit no repo/branch
              CHANGED=$(git ls-files 'static/**' || true)
              DELETED=""
            else
              CHANGED=$(git diff --name-only --diff-filter=AM "$BASE" "$HEAD" -- 'static/**' || true)
              DELETED=$(git diff --name-only --diff-filter=D  "$BASE" "$HEAD" -- 'static/**' || true)
            fi

            # helper: content-type + cache pelas extensões
            guess_headers() {
              local rel="$1"
              local ext="${rel##*.}"
              case "$ext" in
                html)  echo "--content-type 'text/html; charset=utf-8'";;
                json)  echo "--content-type 'application/json' --content-cache-control 'public, max-age=300, must-revalidate'";;
                css)   echo "--content-type 'text/css; charset=utf-8' --content-cache-control 'public, max-age=31536000, immutable'";;
                js)    echo "--content-type 'application/javascript; charset=utf-8' --content-cache-control 'public, max-age=31536000, immutable'";;
                jpg|jpeg) echo "--content-type 'image/jpeg' --content-cache-control 'public, max-age=31536000, immutable'";;
                png)   echo "--content-type 'image/png' --content-cache-control 'public, max-age=31536000, immutable'";;
                webp)  echo "--content-type 'image/webp' --content-cache-control 'public, max-age=31536000, immutable'";;
                gif)   echo "--content-type 'image/gif' --content-cache-control 'public, max-age=31536000, immutable'";;
                svg)   echo "--content-type 'image/svg+xml' --content-cache-control 'public, max-age=31536000, immutable'";;
                ico)   echo "--content-type 'image/x-icon' --content-cache-control 'public, max-age=31536000, immutable'";;
                md)    echo "--content-type 'text/markdown; charset=utf-8'";;
                webmanifest) echo "--content-type 'application/manifest+json' --content-cache-control 'public, max-age=300, must-revalidate'";;
                *)     echo "";;
              esac
            }

            uploaded=0
            skipped=0
            deleted=0

            # apagar blobs removidos no repo
            if [ -n "${DELETED:-}" ]; then
              echo "A remover blobs em falta no repo…"
              while IFS= read -r f; do
                [ -z "$f" ] && continue
                rel="${f#static/}"
                # ignora diretórios
                if az storage blob exists --account-name "$ACCOUNT" -c '$web' -n "$rel" --auth-mode login --query exists -o tsv | grep -q true; then
                  az storage blob delete --account-name "$ACCOUNT" -c '$web' -n "$rel" --auth-mode login >/dev/null
                  echo "  - deleted: $rel"
                  deleted=$((deleted+1))
                fi
              done <<< "$DELETED"
            fi

            # enviar só alterados (por SHA)
            if [ -n "${CHANGED:-}" ]; then
              echo "A avaliar ficheiros alterados…"
              while IFS= read -r f; do
                [ -z "$f" ] && continue
                [ -f "$f" ] || continue
                rel="${f#static/}"
                sha_local="$(sha256sum "$f" | awk '{print $1}')"

                sha_remote="$(az storage blob show \
                  --account-name "$ACCOUNT" \
                  -c '$web' \
                  -n "$rel" \
                  --auth-mode login \
                  --query 'metadata.sha256' -o tsv 2>/dev/null || true)"

                if [ "$sha_local" = "$sha_remote" ]; then
                  echo "  = skip (mesmo SHA): $rel"
                  skipped=$((skipped+1))
                  continue
                fi

                # upload + headers
                az storage blob upload \
                  --account-name "$ACCOUNT" \
                  --auth-mode login \
                  -c '$web' \
                  -f "$f" \
                  -n "$rel" \
                  --overwrite >/dev/null

                hdrs=$(guess_headers "$rel")
                if [ -n "$hdrs" ]; then
                  # shellcheck disable=SC2086
                  az storage blob update \
                    --account-name "$ACCOUNT" \
                    --auth-mode login \
                    -c '$web' \
                    -n "$rel" \
                    $hdrs >/dev/null || true
                fi

                # grava o SHA no metadado
                az storage blob metadata update \
                  --account-name "$ACCOUNT" \
                  --auth-mode login \
                  -c '$web' \
                  -n "$rel" \
                  --metadata "sha256=$sha_local" >/dev/null

                echo "  + uploaded: $rel (sha=${sha_local})"
                uploaded=$((uploaded+1))
              done <<< "$CHANGED"
            fi

            echo "Resumo: uploaded=$uploaded, skipped=$skipped, deleted=$deleted"
