name: Sync Wiki
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  sync:       
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Update submodule (Wiki)
        run: |
          git submodule update --remote --init content/wiki
          if ! git diff --quiet; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add content/wiki
            git commit -m "chore: sync wiki submodule pointer"
            git push
          fi
